[package]
name = "packages.tricti.dev"
version = "0.0.0"
license = "GPL-3.0-or-later"
description = "This is the frontend of the TriCTI Package Manager"

[dependencies]
tricti-compiler = "0.1.0"
trihttp = "0.0.0"